name: fitness_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  intl: ^0.19.0
  supabase_flutter: ^2.3.4
  supabase: ^2.0.8
  animated_notch_bottom_bar: ^1.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-VariableFont_wght.ttf
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: Madimi
      fonts:
        - asset: assets/fonts/MadimiOne-Regular.ttf
    - family: Lilita
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
