// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHh2nPJDrTzqVq6cj_A-xNlq34yUf5bRU',
    appId: '1:982666307983:web:4a9f702a57b33bea3f43fa',
    messagingSenderId: '982666307983',
    projectId: 'fitness-app-d51c4',
    authDomain: 'fitness-app-d51c4.firebaseapp.com',
    storageBucket: 'fitness-app-d51c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAOb-lGNQvIVlhES95Qjob1-jLMGu6bQ',
    appId: '1:982666307983:android:85e98d8ebde03c113f43fa',
    messagingSenderId: '982666307983',
    projectId: 'fitness-app-d51c4',
    storageBucket: 'fitness-app-d51c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUqE6R25FTrZacIP-lYkyyAhy87DKcpA',
    appId: '1:982666307983:ios:12074294b33000033f43fa',
    messagingSenderId: '982666307983',
    projectId: 'fitness-app-d51c4',
    storageBucket: 'fitness-app-d51c4.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhUqE6R25FTrZacIP-lYkyyAhy87DKcpA',
    appId: '1:982666307983:ios:1fb0ef20e6a876623f43fa',
    messagingSenderId: '982666307983',
    projectId: 'fitness-app-d51c4',
    storageBucket: 'fitness-app-d51c4.appspot.com',
    iosBundleId: 'com.example.fitnessApp.RunnerTests',
  );
}
